### ISSUE TITLE
Add JetBrains.Annotations dependency

### ISSUE THREAD

**Issue by tpluscode** [tom-englert/JetBrainsAnnotations.Fody#7]
I see that now `JetBrains.Annotations` isn't bundled in the package anymore. Took me a while to understand why my builds started failing after upgrade.

Would it make sense to include `JetBrains.Annotations` as dependency to nupkg?

**Comment by tom-englert** [comment]
But maybe not everyone is using it, think e.g. of public packages that ship external annotations, but that does not mean that the consumer of the package must use `JetBrains.Annotations`

**Comment by tom-englert** [comment]
Already fixed
